### ISSUE TITLE
AlignIt will remove the last line in a file if it does not end with a line break. 

### ISSUE THREAD

**Issue by ISN-Zurich** [ggarek/brackets-extension-alignit#2]
I tried the following scenario at the end of a file.

```
test = 1;
test2= 2;
test1234 = 1234;
```

Note that the last line must not contain a line break!

If I run AlignIt I get the first two variables properly aligned, but the last line will just disappear. The code looks then like this: 

```
test  = 1;
test2 = 2;

```

This happens only if the last line in a file is included.

**Comment by ggarek** [comment]
Thank you for posting an issue! I have fixed it and updated alingit to v0.1.1.
